import Footer from "./_components/footer";
import Navbar from "./_components/navbar/navbar_P";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className="min-h-full font-secondary antialiased">
        <header className="container mx-auto px-4">
          <nav>
            <Navbar />
          </nav>
        </header>
        <main className="container mx-auto p-4">
          {children}
        </main>
        <footer className="container mx-auto">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
